from yoyo import step

depends = {}

steps = [
    step("CREATE TABLE animals_2 ("
         "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
         "name VARCHAR(255) NOT NULL, "
         "description TEXT, "
         "path VARCHAR(255) NOT NULL)"
         ),
]
