from yoyo import step

depends = {}

steps = [
    step("CREATE TABLE animals ("
         "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
         "parent_id INTEGER REFERENCES animals(id) ON DELETE CASCADE, "
         "name VARCHAR(255) NOT NULL, "
         "description TEXT)"
         ),
]

